from pydantic import BaseModel, Field
from typing import List, Optional

class Requirement(BaseModel):
    id: str = Field(..., description="Unique requirement ID, e.g. RQ-01")
    description: str = Field(..., description="Text description of the requirement")
    cases_count: int = Field(0, description="Total number of test cases covering this requirement")

class ClarifyingQuestion(BaseModel):
    id: str = Field(..., description="Unique question ID, e.g. Q-01")
    requirement_id: str = Field(..., description="Linked requirement ID, e.g. RQ-01")
    question: str = Field(..., description="Question text generated by LLM")

class UserAnswer(BaseModel):
    question_id: str = Field(..., description="ID of the question")
    question: str = Field(..., description="Text of the question")
    answer: str = Field(..., description="Answer provided by user")

class TestScenario(BaseModel):
    id: str = Field(..., description="Unique test case ID, e.g. TC-001")
    name: str = Field(..., description="Test case name")
    priority: str = Field("П2", description="Priority level: П1 (Critical), П2 (Important), П3 (Low)")
    preconditions: List[str] = Field(default_factory=list, description="Preconditions list")
    steps: List[str] = Field(default_factory=list, description="Numbered steps list")
    expected_results: List[str] = Field(default_factory=list, description="Numbered expected results list")
    coverage: List[str] = Field(default_factory=list, description="List of covered requirement IDs (e.g. RQ-01)")

class AnalysisRequest(BaseModel):
    requirements_text: str
    additional_info: Optional[str] = None
    old_scenarios_text: Optional[str] = None

class RequirementsResponse(BaseModel):
    requirements: List[Requirement]

class QuestionsGenerationRequest(BaseModel):
    requirements: List[Requirement]

class QuestionsResponse(BaseModel):
    questions: List[ClarifyingQuestion]

class ScenariosGenerationRequest(BaseModel):
    requirements: List[Requirement]
    answers: List[UserAnswer]

class ScenariosResponse(BaseModel):
    scenarios: List[TestScenario]

class CompareRequest(BaseModel):
    old_scenarios_text: str
    new_scenarios: List[TestScenario]

class CompareResponse(BaseModel):
    changes_summary: str = Field(..., description="Detailed textual diff/report of changes")
    added: List[str] = Field(default_factory=list, description="List of added scenario IDs")
    removed: List[str] = Field(default_factory=list, description="List of removed scenario IDs")
    modified: List[str] = Field(default_factory=list, description="List of modified scenario IDs")
